import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from jinja2 import Template

EMAIL_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; background:#f4f4f4; margin:0; padding:20px; color:#222; }
  .wrap { max-width:860px; margin:0 auto; background:#fff; padding:28px 32px; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.05); }
  h1 { font-size:22px; margin:0 0 6px; }
  .meta { color:#666; font-size:13px; margin-bottom:20px; }
  .regime { background:#e8f1ff; padding:10px 14px; border-radius:6px; margin-bottom:18px; font-size:13px; }
  .regime strong { color:#0052cc; }
  h2 { font-size:16px; margin:24px 0 8px; border-bottom:2px solid #eee; padding-bottom:6px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th { background:#f8f8f8; text-align:left; padding:8px 10px; border-bottom:1px solid #ddd; font-weight:600; }
  td { padding:8px 10px; border-bottom:1px solid #f0f0f0; }
  .tier5 { background:#e7f7ee; }
  .tier4 { background:#f0faf3; }
  .tier3 { background:#fff; }
  .tier0 { background:#fef2f2; color:#888; }
  .ticker { font-weight:600; color:#0052cc; }
  .tier-badge { display:inline-block; padding:2px 8px; border-radius:4px; font-weight:600; font-size:11px; }
  .t5 { background:#0d7b34; color:#fff; }
  .t4 { background:#1a9850; color:#fff; }
  .t3 { background:#4a90e2; color:#fff; }
  .t2 { background:#999; color:#fff; }
  .t0 { background:#c94545; color:#fff; }
  .footer { margin-top:30px; font-size:11px; color:#999; text-align:center; }
  .empty { text-align:center; color:#666; font-style:italic; padding:24px; background:#fafafa; border-radius:6px; }
</style>
</head>
<body>
<div class="wrap">
  <h1>Swing Trading Scan — {{ scan_date }}</h1>
  <div class="meta">Universe scanned: {{ universe_size }} &middot; Fast-filter survivors: {{ fast_survivors }} &middot; Fully scored: {{ scored_total }} &middot; API calls: {{ api_calls }}</div>

  <div class="regime">
    Market Regime: <strong>{{ regime }}</strong> &middot; VIX {{ vix }}
  </div>

  {% if top_tickets %}
    <h2>Top {{ top_tickets|length }} Candidates</h2>
    <table>
      <thead>
        <tr>
          <th>Tier</th><th>Ticker</th><th>Name</th><th>Price</th><th>Stop</th><th>Phase 1 Target</th><th>Runner</th><th>R/R</th><th>Pillars</th>
        </tr>
      </thead>
      <tbody>
        {% for t in top_tickets %}
          <tr class="tier{{ (t.tier|int) if t.tier is number else 0 }}">
            <td><span class="tier-badge t{{ (t.tier|int) if t.tier is number else 0 }}">T{{ t.tier }}</span></td>
            <td class="ticker">{{ t.ticker }}</td>
            <td>{{ t.name[:28] }}</td>
            <td>${{ "%.2f"|format(t.price) }}</td>
            <td>${{ "%.2f"|format(t.stop_loss) }}</td>
            <td>${{ "%.2f"|format(t.phase1_target) }}</td>
            <td>${{ "%.2f"|format(t.runner_target) }}</td>
            <td>{{ t.risk_reward }}</td>
            <td>{{ t.pillars_passed }}/{{ t.applicable_pillars }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="empty">No candidates passed all gates today. Patience is a position.</div>
  {% endif %}

  {% if rejected_tickets %}
    <h2>Rejected at Gate ({{ rejected_tickets|length }})</h2>
    <table>
      <thead><tr><th>Ticker</th><th>Name</th><th>Pillars</th><th>Failed Gates</th></tr></thead>
      <tbody>
        {% for t in rejected_tickets %}
          <tr class="tier0">
            <td class="ticker">{{ t.ticker }}</td>
            <td>{{ t.name[:28] }}</td>
            <td>{{ t.pillars_passed }}/{{ t.applicable_pillars }}</td>
            <td>{{ t.hard_gate_fails|join(', ') }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}

  <div class="footer">Generated by swing-trading-scanner &middot; v3.1 spec &middot; Long equity only, 1-3 month horizon</div>
</div>
</body>
</html>"""


def render_email(scan):
    tickets = scan.get("tickets") or [r["ticket"] for r in scan.get("results", [])]
    top = [t for t in tickets if t["tier"] and t["tier"] >= 3][:25]
    rejected = [t for t in tickets if not t.get("tier") or t["tier"] == 0][:10]
    regime = scan["vix_regime"]
    vix_val = regime.get("vix")
    t = Template(EMAIL_TEMPLATE)
    return t.render(
        scan_date=scan["scan_date"],
        universe_size=scan["universe_size"],
        fast_survivors=scan["fast_filter_survivors"],
        scored_total=scan["scored_total"],
        api_calls=scan["api_calls"],
        regime=regime.get("regime", "unknown"),
        vix=round(vix_val, 2) if vix_val is not None else "n/a",
        top_tickets=top,
        rejected_tickets=rejected,
    )


def send_email(html, scan_date, recipient=None):
    gmail_user = os.environ["GMAIL_USER"]
    gmail_password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = recipient or gmail_user

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Swing Scan {scan_date}"
    msg["From"] = gmail_user
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(gmail_user, gmail_password)
        server.sendmail(gmail_user, recipient, msg.as_string())
    return True
